-- Migration 013: Update Banners, Offers, and Coupons schema for full marketing management

ALTER TABLE banners
ADD COLUMN IF NOT EXISTS subtitle VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE offers
ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) DEFAULT 'percentage',
ADD COLUMN IF NOT EXISTS discount_value DECIMAL(10, 2) DEFAULT 0.00 CHECK (discount_value >= 0),
ADD COLUMN IF NOT EXISTS offer_scope VARCHAR(20) DEFAULT 'store',
ADD COLUMN IF NOT EXISTS target_product_id UUID REFERENCES products(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS target_category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE coupons
ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) DEFAULT 'percentage',
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS max_discount_amount DECIMAL(10, 2) DEFAULT NULL CHECK (max_discount_amount >= 0),
ADD COLUMN IF NOT EXISTS usage_limit INTEGER DEFAULT NULL CHECK (usage_limit >= 0),
ADD COLUMN IF NOT EXISTS usage_per_user INTEGER DEFAULT 1 CHECK (usage_per_user >= 1),
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_banners_display ON banners(display_order);
CREATE INDEX IF NOT EXISTS idx_banners_deleted ON banners(is_deleted);
CREATE INDEX IF NOT EXISTS idx_offers_deleted ON offers(is_deleted);
CREATE INDEX IF NOT EXISTS idx_coupons_deleted ON coupons(is_deleted);
