-- Migration 017: Ensure all missing columns & tables exist across products, notifications, banners, reviews, categories, and users

-- 1. Products Table Extensions
ALTER TABLE products
ADD COLUMN IF NOT EXISTS slug VARCHAR(150) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS brand VARCHAR(100) DEFAULT 'Krishna',
ADD COLUMN IF NOT EXISTS discount_price DECIMAL(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS short_description TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cost_price DECIMAL(10, 2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_bestseller BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_new_arrival BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 2. Notifications Table Verification
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    is_admin BOOLEAN DEFAULT FALSE,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;

-- 3. Banners Table Extensions
ALTER TABLE banners
ADD COLUMN IF NOT EXISTS subtitle TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS button_text VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS button_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;

-- 4. Reviews Table Extensions
ALTER TABLE reviews
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'Approved';

-- 5. Categories Table Extensions
ALTER TABLE categories
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) DEFAULT NULL;

-- 6. Users Table Extensions
ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone VARCHAR(30) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT NULL;
